### ISSUE TITLE
Plugin doesn't ignore certain imgs with specific classes

### ISSUE THREAD

**Issue by canha42** [canha42/pinterest-pin-it#3]
Image tags with specific classes (such as .wp_smiley and other user defined classes) should be ignored by the script.

Search ppibfi_pinterest.php for "Issue #3"

**Comment by pererinha** [comment]
I fixed this issue. I split the function pibfi_Engine in more two functions pibfi_Engine_add_pin and pibfi_Engine_should_it_has_pin.

The first one add the pin at each image, but before that it call the function pibfi_Engine_should_it_has_pin in order to check if the image shoud or shouldn't has the pin. 

The function pibfi_Engine_should_it_has_pin verify if the image has certain css classes like .wp_smiley or wp-thumb if it does it returns false, what means this image shoudn't have the pin.

**Comment by pererinha** [comment]
The ignored classes are statics, it should be dynamic.

**Comment by pererinha** [comment]
Done.
