### ISSUE TITLE
Lazy Loading

### ISSUE THREAD

**Issue by mikezielonka** [canha42/pinterest-pin-it#44]
When images are lazy loaded the pinit button does not load properly.

To duplicate: install bj lazy load, enable lazy loading on images and load script in the footer (or header).

Example: http://wholelifestylenutrition.com/articles/why-i-love-my-jawbone-up/

**Comment by chvillanuevap** [comment]
Have you tried the Lazy Load plugin by Automattic? It seems to be compatible with this plugin.

**Comment by chvillanuevap** [comment]
It seems the Pin it button will load correctly, but the link to the image will not.

**Comment by chvillanuevap** [comment]
The problem is that the filter applied to the content with this plugin has a priority of 100, while the Lazy Load plugin by Automattic has a priority of 99. By the time the Pinterest plugin get its hands on the images, they have all been manipulated and modified by the Lazy Load plugin. A simple solution is to modify the priority. Give this plugin a priority of 98 rather than 100 and it should work.

``` php
if (!is_admin() && stripos($_SERVER['HTTP_USER_AGENT'], 'mobile') != true) {
    wp_enqueue_style('pibfi_pinterest', XCPIN_PATH.'ppibfi_pinterest.css');
    wp_enqueue_script('pibfi_pinterest', XCPIN_PATH.'ppibfi_pinterest.js', array('jquery'));
    add_filter('the_content', 'pibfi_Engine', 98); // The engine  <!------------------- HERE
    add_action('wp_head', 'cWGlobal'); // Add function to wp_head();
}
```

**Comment by canha42** [comment]
Thanks @chvillanuevap - will be added to 1.1 after tested!
